# Generated by Django 4.2.5 on 2023-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('email', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
            ],
        ),
    ]
