# Generated by Django 4.2.5 on 2023-10-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0003_alter_admins_email_alter_usuarios_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='admins',
            name='role',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfc.school'),
        ),
    ]
