# Generated by Django 4.2.5 on 2023-10-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='selfc.file'),
        ),
    ]
