# Generated by Django 4.2.5 on 2023-10-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0008_pregunta_respuesta_resultado_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='completed_space',
        ),
    ]
