# Generated by Django 4.2.5 on 2023-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0010_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='resp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
