# Generated by Django 4.2.5 on 2023-10-09 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0011_pregunta_resp_delete_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='namepregunta',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selfc.test'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='test_type',
            field=models.CharField(max_length=50),
        ),
    ]
