# Generated by Django 4.2.5 on 2023-10-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0012_remove_pregunta_namepregunta_pregunta_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
