# Generated by Django 4.2.5 on 2023-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfc', '0013_alter_pregunta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
